import day1 from "./day1/index.ts";
import day2 from "./day2/index.ts";
import day3 from "./day3/index.ts";
import day4 from "./day4/index.ts";
import day5 from "./day5/index.ts";
import day6 from "./day6/index.ts";
import day7 from "./day7/index.ts";
import day8 from "./day8/index.ts";
import day9 from "./day9/index.ts";

day1();
console.log("———————");
day2();
console.log("———————");
day3();
console.log("———————");
day4();
console.log("———————");
day5();
console.log("———————");
day6();
console.log("———————");
day7();
console.log("———————");
day8();
console.log("———————");
day9();
